name = "HBPack"
author = "Jaegyu"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8d13948a16c56600a4fd6b8b6c8a06fa2cd721359d1925944148df0d87816a6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.221"
